on:
  push:
    branches:
      - master1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'testing Github actions'
        run: pwd
        
      - name: 'testing the printing'
        run: echo yousry
