on:
  push:
    branches:
      - master1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  

      - name: "login to Docker hub"
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_TOKEN }}
     
      - name: "Building docker image"
        run: docker built -t myimage .

      - name: "pusing to Docker hub"
        run: docker push ${{ secrets.DOCKER_USERNAME }}/myimage
