on:
  push:
    branches:
      - master1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  

      - name: "login to Docker hub"
        run: docker login --username yousrybahbah --password dckr_pat_azV1T7VVnVgIRm4fPKdrjpBdgjg

     